/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package rpc.service;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface RpcHttpAppHost {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"RpcHttpAppHost\",\"namespace\":\"rpc.service\",\"types\":[{\"type\":\"record\",\"name\":\"HttpAppHost\",\"namespace\":\"rpc.domain\",\"fields\":[{\"name\":\"reportTime\",\"type\":[\"string\",\"null\"]},{\"name\":\"appType\",\"type\":[\"int\",\"null\"]},{\"name\":\"appSubType\",\"type\":[\"string\",\"null\"]},{\"name\":\"userIp\",\"type\":[\"string\",\"null\"]},{\"name\":\"userPort\",\"type\":[\"int\",\"null\"]},{\"name\":\"appServerIp\",\"type\":[\"string\",\"null\"]},{\"name\":\"appServerPort\",\"type\":[\"string\",\"null\"]},{\"name\":\"host\",\"type\":[\"string\",\"null\"]},{\"name\":\"cellid\",\"type\":[\"string\",\"null\"]},{\"name\":\"attemps\",\"type\":[\"int\",\"null\"]},{\"name\":\"accepts\",\"type\":[\"int\",\"null\"]},{\"name\":\"trafficUL\",\"type\":[\"long\",\"null\"]},{\"name\":\"tracfficDL\",\"type\":[\"long\",\"null\"]},{\"name\":\"retranUL\",\"type\":[\"long\",\"null\"]},{\"name\":\"retranDL\",\"type\":[\"long\",\"null\"]},{\"name\":\"failCount\",\"type\":[\"int\",\"null\"]},{\"name\":\"transDelay\",\"type\":[\"long\",\"null\"]}]}],\"messages\":{\"sendHttpAppHost\":{\"request\":[{\"name\":\"httpAppHost\",\"type\":\"rpc.domain.HttpAppHost\"}],\"response\":\"null\"},\"sendMap\":{\"request\":[{\"name\":\"HttpAppHostMap\",\"type\":{\"type\":\"map\",\"values\":\"rpc.domain.HttpAppHost\"}}],\"response\":\"null\"}}}");
  /**
   */
  java.lang.Void sendHttpAppHost(rpc.domain.HttpAppHost httpAppHost) throws org.apache.avro.AvroRemoteException;
  /**
   */
  java.lang.Void sendMap(java.util.Map<java.lang.CharSequence,rpc.domain.HttpAppHost> HttpAppHostMap) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends RpcHttpAppHost {
    public static final org.apache.avro.Protocol PROTOCOL = rpc.service.RpcHttpAppHost.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendHttpAppHost(rpc.domain.HttpAppHost httpAppHost, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void sendMap(java.util.Map<java.lang.CharSequence,rpc.domain.HttpAppHost> HttpAppHostMap, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}